### ISSUE TITLE
Add cross plattform support

### ISSUE THREAD

**Issue by tschnz** [collective-soundworks/soundworks-template#7]
Hey, Win10 64bit here. Tried to use `npm install` but cmd can't handle `&&` and `cp` in the postinstall script.

In [package.json](https://github.com/collective-soundworks/soundworks-template/blob/master/package.json) I changed the following:

```sh
"repository": {
    ...
    "run-script-os": "^1.1.5",
    ...
  },
```

and

```sh
  "scripts": {
    ...
    "postinstall": "run-script-os",
    "postinstall:default": "mkdir -p .vendors/public && cp -R node_modules/@webcomponents/webcomponentsjs .vendors/public",
    "postinstall:win32": "Xcopy /E /I /H /Y node_modules\\@webcomponents\\webcomponentsjs .vendors\\public",
    ...
  },
```

So the default should be used for every OS but Windows. Couldn't test if `npm install` now still works on other systems.

**Comment by b-ma** [comment]
Hi,

Thanks for reporting that and give an actual solution, I just tested on my mac and it seems to work properly.

I just wondering if it wouldn't finally be more appropriate to make a js script and delegate these systems commands to node (+ it allows to avoid an additional dependency):
```
 "scripts": {
    ...
    "postinstall": "node ./bin/postinstall.js",
    ...
  },
```
I can make a sketch it if you are willing to test it, or happy to test it if you want to contribute on this.

**Comment by tschnz** [comment]
Your proposed solution was my second thought but I decided against it for cleaner folder structure (no ./bin/) in favor of a dependency. On the other hand I'm somewhat new to node.js ;)

I'm happy to test that on Windows and/or make it work given an initial .js script :)

**Comment by b-ma** [comment]
Yes, that's a good point, probably better to make that folder hidden for most users.
I will sketch that in the afternoon and let you know when its ready to be tested.

Thanks !

**Comment by b-ma** [comment]
ok I have made a test here : https://github.com/collective-soundworks/soundworks-template/tree/patch/cross-platform-support 

I finally agree with you that the extra folder is quite cumbersome, so I will keep your original solution while we don't have more stuff to do in the postinstall step. However I would be interested to see if it works as expected, so if you could try and tell me that would be nice! 

thanks

**Comment by b-ma** [comment]
so if you want to make a PR (in the v3 branch) let me know and I will wait for it, otherwise I'll integrate your patch shortly.

**Comment by tschnz** [comment]
Using your .js script works, I can `npm install` and `npm run dev` without problems. 

BUT: In the script you now just copy webcomponents-bundle.js. Previously node_modules/@webcomponents/webcomponentsjs was copied recursively. I can make a PR using run-script-os that copies only this one file? What's your thought on that? Do you need the other stuff?

**Comment by b-ma** [comment]
ok cool, good news (at least I know such strategy can work on windows too)

Yes I did like that because it's quite complicated to copy the whole folder with only native node modules and we indeed dont need the other files. 
But, I think the first approach was actually better, because if for some reason we need some other files, they are just there waiting, no need to change the install scripts. So just go with copying the whole folder it's both more simple and more opened to changes. 
I'll just wait for your PR then, I'm not very fluent with PRs but if you can do it against the v3 branch it would be perfect.

Thanks again
