### ISSUE TITLE
Windows: Watch process doesn't seem to work

### ISSUE THREAD

**Issue by schlenger** [collective-soundworks/soundworks-template#9]
Checking out the plain project and running `npm run dev`, the file watcher is not working and manually restarting the application is needed.

System: Windows 10, Version 10.0.19042 Build 19042.

Side note: I've also had some trouble with the babel config and needed to add `"loose": true,` here: https://github.com/collective-soundworks/soundworks-template-build/blob/master/src/build-application.js#L81

**Comment by tschnz** [comment]
The watcher (chokidar) works correctly when in files in ./.bulid/ are changed (because of [this](https://github.com/collective-soundworks/soundworks-template-build/blob/856691ac846f4aa736b2c70523c36f7066486092/src/watch-process.js#L65)) but not when changing/saving things in ./src/.

**Comment by schlenger** [comment]
> The watcher (chokidar) works correctly when in files in ./.bulid/ are changed (because of this) but not when changing/saving things in ./src/.

Yes. However, it would be nice to register changes while developing the application. Is there a reason why it is how it is right now?

**Comment by b-ma** [comment]
No there is actually no reason, the steps for the build are supposed to be: 

1. transpile (from `src` to `.build`) when a change is seen in `src` 
2. restart server if a file changed in `.build/server`, 

This way the process is (when it works...) very simple and no possible concurrency issues.

If the server restarts when a file is saved in `.build` it means the transpile step does not work (which is actually weird and new). As I discovered the "loose: true" issue today too, I hope this is only a side-effect of this problem (even if on my side MacOS 11, the server restarts has expected when I save a file...).

I just pushed and published a new version 3.0.3 that fixes the "loose: true" issue and some other weirdness, let me know if it is back to normal for you

**Comment by tschnz** [comment]
The "loose: true" thing is resolved with this!

But to make sure we're on the same page with the watcher: What is your workflow when developing an application? When I'm using `npm run dev` and write my piece of code somewhere in ./src and save it nothing happens. Is that behaviour is intended? How can I achieve the behaviour of the server restarting automatically or building/transpiling the changed files automatically?

**Comment by b-ma** [comment]
ok cool for the `loose: true`

The workflow should be :
1. If you save a file in `src/server` the file should be transpiled to `.build/server` and the server should restart
2. if you save a file in `src/clients` the file should transpiled and/or bundled (depending of how the client is declared in `config/application.json` but the server does not restart in this case.

Currently, file that are not located in `server` or `clients` are just ignored, but this is an issue that I have to solve when I found the time: cf. https://github.com/collective-soundworks/soundworks/issues/23

Let me know if this helps

**Comment by schlenger** [comment]
@b-ma Okay, this sounds like a behaviour one wants to use.

For me this is currently not working: Even when running the server with `npm run dev`, not files are compiled afterwards when changing something in `src/server` nor `src/clients`. 

As specified above I'm running Windows 10, Version 10.0.19042 Build 19042 right now if this is an operating system related bug. I can test it on my Linux machine tomorrow.

**Comment by schlenger** [comment]
I can confirm that the solution is working - and it's sooo much faster then recompiling the whole server. Thank you.

**Comment by b-ma** [comment]
Perfect ! Let's close that then
